import markdown

def generate_html_report(md_text: str, output_path: str) -> str:
    """将数据分析 Markdown 转换为极具商业质感的 HTML"""
    
    html_content = markdown.markdown(md_text, extensions=['tables', 'fenced_code'])
    
    # 🌟 极客感数据分析大屏 UI 规范
    html_template = f"""
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ZClaw 智能数据洞察大屏</title>
        <style>
            :root {{
                --brand: #0ea5e9;
                --bg: #e2e8f0;
                --panel: #ffffff;
                --text: #334155;
            }}
            body {{
                font-family: 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                background-color: var(--bg);
                color: var(--text);
                padding: 40px 20px;
                line-height: 1.6;
            }}
            .dashboard {{
                max-width: 1100px;
                margin: 0 auto;
                background: var(--panel);
                padding: 50px;
                border-radius: 20px;
                box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
            }}
            h1 {{ text-align: center; color: #0f172a; font-size: 2.5rem; letter-spacing: -0.02em; margin-bottom: 10px; }}
            h1::after {{ content: ""; display: block; width: 80px; height: 4px; background: var(--brand); margin: 20px auto; border-radius: 2px; }}
            h2 {{ color: #0f172a; margin-top: 50px; padding-bottom: 10px; border-bottom: 2px solid #cbd5e1; }}
            h3 {{ color: var(--brand); }}
            
            /* 图表展示区美化 */
            img {{
                display: block;
                max-width: 90%;
                margin: 40px auto;
                border-radius: 12px;
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
                border: 1px solid #e2e8f0;
                transition: transform 0.3s ease;
            }}
            img:hover {{ transform: scale(1.02); }}
            
            table {{ width: 100%; border-collapse: collapse; margin: 30px 0; }}
            th, td {{ border-bottom: 1px solid #e2e8f0; padding: 12px; text-align: left; }}
            th {{ font-weight: bold; color: #0f172a; }}
            tr:hover {{ background-color: #f8fafc; }}
            
            .footer {{ text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.9rem; }}
        </style>
    </head>
    <body>
        <div class="dashboard">
            {html_content}
            <div class="footer">Generated by AI Agent Architecture • Data Analytics Module</div>
        </div>
    </body>
    </html>
    """
    return html_template